repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
        name: running terraform fmt
        description: Checks if the terraform code format is valid.
        stages: [commit]
      - id: terraform_docs
        name: Running Terraform Docs
        description: Generates terraform documentation.(Readme File)
        args:
          - '--args=--lockfile=false'
          - '--args=--config=.terraform-docs.yml'
      - id: terraform_tflint
        name: terraform tflint
        description: Automatic terraform linting.
        args:
            - config=.tflint.hcl
        exclude: examples
      - id: terraform_validate
        name: terraform validate
        description: Terraform code validator.
        exclude: examples
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
        name: check merge conflict
        description: Check for files that contain merge conflict strings.
      - id: end-of-file-fixer
        name: end of file fixer
        description: Let's be sure that a new line has been added to the end of the file.
      - id: trailing-whitespace
        name: trailing whitespace
        description: Automatically remove trailing whitespace before committing.
      - id: detect-private-key
        name: detect-private-key
        description: Detect if any Private key was defined
      - id: detect-aws-credentials
        name: detect-aws-credentials
        description: find if any aws credentials are defined in module
        args: [--allow-missing-credentials]
      - id: check-yaml
        name: check yaml
        description: checks yaml files for parseable syntax.
        entry: check-yaml
        language: python
        types: [yaml]
