---
formatter: markdown table

version: ">= 0.16.0, < 1.0.0"

output:
  file: README.md
  mode: inject

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
