name: Pre-Commit

on:
  pull_request:
  push:
    branches:
      - master
      - main 

jobs:
    compositeInputs:
      name: Collect workflow inputs
      runs-on: ubuntu-latest
      outputs:
        directories: ${{ steps.dirs.outputs.directories }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Get root directories
          id: dirs
          uses: clowdhaus/terraform-composite-actions/directories@v1.9.0